Document: vulkan-validationlayers
Title: Debian vulkan-validationlayers Manual
Author: <insert document author here>
Abstract: This manual describes what vulkan-validationlayers is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vulkan-validationlayers/vulkan-validationlayers.sgml.gz

Format: postscript
Files: /usr/share/doc/vulkan-validationlayers/vulkan-validationlayers.ps.gz

Format: text
Files: /usr/share/doc/vulkan-validationlayers/vulkan-validationlayers.text.gz

Format: HTML
Index: /usr/share/doc/vulkan-validationlayers/html/index.html
Files: /usr/share/doc/vulkan-validationlayers/html/*.html
